FROM node:22.5.1-alpine AS build-stage

# Set the working directory for all build
WORKDIR /usr/src/app

# Copy dep
COPY package.json package.json
COPY package-lock.json package-lock.json

# install dependencies in CI mode (production deps install)
RUN npm ci

# Copy the rest of the application code to the working directory
COPY . .

# build the next app
RUN npm run build

# remove dev dependencies
RUN npm prune --production

# New Stage to build prod
FROM node:22.5.1-alpine

# copy from build-stage
COPY --from=build-stage /usr/src/app/package.json ./package.json
COPY --from=build-stage /usr/src/app/node_modules ./node_modules
COPY --from=build-stage /usr/src/app/.next ./.next
COPY --from=build-stage /usr/src/app/public ./public

# port for app
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start"]
