FROM node:22.5.1-alpine as BUILD_IMAGE

WORKDIR /app

# Copy dep
COPY package.json package-lock.json ./

# install dependencies in CI mode (production deps install)
RUN npm ci
COPY . .

# build
RUN yarn build

# remove dev dependencies
RUN npm prune --production

# New Stage to build prod
FROM node:22.5.1-alpine

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public

# port for app
EXPOSE 3000

CMD ["npm", "run", "start"]
