name: Pull Request Workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
  # Trigger the workflow on push to staging and production branches
  push:
    branches:
      - staging
      - production

jobs:
  pull_request_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/cache@v3
        name: Setup NPM cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint check
        run: npm run lint

      - name: Run Prettier check
        run: npm run format-check

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test:ci
